### ISSUE TITLE
Hide list of options once shown

### ISSUE THREAD

**Issue by lievcin** [amsify42/jquery.amsify.suggestags#30]
As per issue #23 the options can be shown. This is working as intended, but there's one issue I found. Once shown, the options cannot be hidden away again. If one has a form with several fields, this overlaps with the fields below.

Thank you!

**Comment by amsify42** [comment]
I have fixed and hiding the list when focus is out of input. Please let me know if its working fine.

**Comment by lievcin** [comment]
@amsify42 not working as intended. I have several inputs with the plugin on them. For some reason it hides in some when you click away, in others it doesn't. 

I'm initialising them like this:

```
	$('.tags_field').each(function(){
		var suggestions = $(this).data("suggestions")
		amsifySuggestags = new AmsifySuggestags($(this));
		amsifySuggestags._settings({
			type :'amsify',
	  	suggestions: suggestions,
	  	showAllSuggestions: true
		})
		amsifySuggestags._init();
	});
```

maybe there is something in the way they're being initialised?

**Comment by amsify42** [comment]
One more thing you need to notice that suggestions list will hide where there is no text in input field.

**Comment by lievcin** [comment]
@amsify42 I'm still unable to make the menu hide once shown... Using the latest commit.
